name: Test PyGeoprocessing

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    env:
        PACKAGES: "pytest flake8"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
      with:
          # Fetch all history so that setuptool_scm can build the correct version string.
          fetch-depth: 0

    - name: setup-miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: anaconda-client-env
        python-version: 3.7
        auto-activate-base: true
    - name: Install dependencies
      shell: bash
      run: conda upgrade -y pip setuptools

    - name: Install PyGeoprocessing (Linux, Mac)
      if: matrix.os != 'windows-latest'
      shell: bash -l {0}
      run: |
          conda install --file requirements.txt
          conda install $PACKAGES
          python setup.py install
          printenv
          find /usr -name proj.db

    - name: Test with pytest
      shell: bash -l {0}
      run: pytest -s
      
    - name: Test with pytest
      shell: bash -l {0}
      run: pytest -s
